import { Injectable } from '@angular/core';
import jsPDF from 'jspdf';
import { Roadmap } from './gemini.service';

@Injectable({
    providedIn: 'root'
})
export class PdfService {
    generateRoadmapPDF(roadmap: Roadmap, userName: string = 'Career Comeback'): void {
        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.getWidth();
        const margin = 20;
        let y = 20;

        // Header
        doc.setFontSize(24);
        doc.setTextColor(60, 179, 165); // Primary color
        doc.text('Career Comeback Roadmap', pageWidth / 2, y, { align: 'center' });
        y += 15;

        // Overall Goal
        doc.setFontSize(12);
        doc.setTextColor(100, 100, 100);
        doc.text(`Goal: ${roadmap.overallGoal}`, margin, y);
        y += 10;
        doc.text(`Estimated Hours: ${roadmap.estimatedHours}`, margin, y);
        y += 15;

        // Weeks
        roadmap.weeks.forEach((week, index) => {
            // Check if we need a new page
            if (y > 250) {
                doc.addPage();
                y = 20;
            }

            // Week header
            doc.setFontSize(16);
            doc.setTextColor(0, 0, 0);
            doc.text(`Week ${week.week}: ${week.title}`, margin, y);
            y += 10;

            // Goals
            doc.setFontSize(10);
            doc.setTextColor(60, 60, 60);
            doc.text('Goals:', margin, y);
            y += 6;
            doc.setFontSize(9);
            week.goals.forEach(goal => {
                const lines = doc.splitTextToSize(`• ${goal}`, pageWidth - 2 * margin);
                doc.text(lines, margin + 5, y);
                y += lines.length * 5;
            });

            y += 3;

            // Topics
            doc.setFontSize(10);
            doc.setTextColor(60, 60, 60);
            doc.text('Topics:', margin, y);
            y += 6;
            doc.setFontSize(9);
            week.topics.forEach(topic => {
                const lines = doc.splitTextToSize(`• ${topic}`, pageWidth - 2 * margin);
                doc.text(lines, margin + 5, y);
                y += lines.length * 5;
            });

            y += 3;

            // Resources
            doc.setFontSize(10);
            doc.setTextColor(60, 60, 60);
            doc.text('Resources:', margin, y);
            y += 6;
            doc.setFontSize(9);
            week.resources.forEach(resource => {
                const lines = doc.splitTextToSize(`• ${resource}`, pageWidth - 2 * margin);
                doc.text(lines, margin + 5, y);
                y += lines.length * 5;
            });

            y += 3;

            // Projects
            doc.setFontSize(10);
            doc.setTextColor(60, 60, 60);
            doc.text('Projects:', margin, y);
            y += 6;
            doc.setFontSize(9);
            week.projects.forEach(project => {
                const lines = doc.splitTextToSize(`• ${project}`, pageWidth - 2 * margin);
                doc.text(lines, margin + 5, y);
                y += lines.length * 5;
            });

            y += 12; // Space between weeks
        });

        // Footer
        const totalPages = doc.getNumberOfPages();
        for (let i = 1; i <= totalPages; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(150, 150, 150);
            doc.text(
                `Generated by Career Comeback Coach | Page ${i} of ${totalPages}`,
                pageWidth / 2,
                doc.internal.pageSize.getHeight() - 10,
                { align: 'center' }
            );
        }

        // Save
        doc.save(`comeback-roadmap-${Date.now()}.pdf`);
    }
}
